# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/sdm845-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lge/sdm845-common/proprietary/bin/wfdservice:system/bin/wfdservice \
    vendor/lge/sdm845-common/proprietary/etc/cne/SwimConfig.xml:system/etc/cne/SwimConfig.xml \
    vendor/lge/sdm845-common/proprietary/etc/cne/andsfCne.xml:system/etc/cne/andsfCne.xml \
    vendor/lge/sdm845-common/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    vendor/lge/sdm845-common/proprietary/etc/dpm/nsrm/NsrmConfiguration.xml:system/etc/dpm/nsrm/NsrmConfiguration.xml \
    vendor/lge/sdm845-common/proprietary/etc/init/wfdservice.rc:system/etc/init/wfdservice.rc \
    vendor/lge/sdm845-common/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/lge/sdm845-common/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    vendor/lge/sdm845-common/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    vendor/lge/sdm845-common/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    vendor/lge/sdm845-common/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/lge/sdm845-common/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/lge/sdm845-common/proprietary/etc/permissions/telephonyservice.xml:system/etc/permissions/telephonyservice.xml \
    vendor/lge/sdm845-common/proprietary/etc/sysconfig/qti_whitelist.xml:system/etc/sysconfig/qti_whitelist.xml \
    vendor/lge/sdm845-common/proprietary/etc/wfdconfig.xml:system/etc/wfdconfig.xml \
    vendor/lge/sdm845-common/proprietary/etc/wfdconfigsink.xml:system/etc/wfdconfigsink.xml \
    vendor/lge/sdm845-common/proprietary/framework/QtiTelephonyServicelibrary.jar:system/framework/QtiTelephonyServicelibrary.jar \
    vendor/lge/sdm845-common/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    vendor/lge/sdm845-common/proprietary/framework/com.qti.dpmframework.jar:system/framework/com.qti.dpmframework.jar \
    vendor/lge/sdm845-common/proprietary/framework/com.quicinc.cne.api-V1.0-java.jar:system/framework/com.quicinc.cne.api-V1.0-java.jar \
    vendor/lge/sdm845-common/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
    vendor/lge/sdm845-common/proprietary/framework/dpmapi.jar:system/framework/dpmapi.jar \
    vendor/lge/sdm845-common/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/lge/sdm845-common/proprietary/framework/tcmclient.jar:system/framework/tcmclient.jar \
    vendor/lge/sdm845-common/proprietary/lib/com.qualcomm.qti.ant@1.0.so:system/lib/com.qualcomm.qti.ant@1.0.so \
    vendor/lge/sdm845-common/proprietary/lib/com.qualcomm.qti.dpm.api@1.0.so:system/lib/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/lge/sdm845-common/proprietary/lib/com.qualcomm.qti.wifidisplayhal@1.0.so:system/lib/com.qualcomm.qti.wifidisplayhal@1.0.so \
    vendor/lge/sdm845-common/proprietary/lib/libFileMux.so:system/lib/libFileMux.so \
    vendor/lge/sdm845-common/proprietary/lib/libOmxMux.so:system/lib/libOmxMux.so \
    vendor/lge/sdm845-common/proprietary/lib/libaptX_encoder.so:system/lib/libaptX_encoder.so \
    vendor/lge/sdm845-common/proprietary/lib/libdisplayconfig.so:system/lib/libdisplayconfig.so \
    vendor/lge/sdm845-common/proprietary/lib/libdpmctmgr.so:system/lib/libdpmctmgr.so \
    vendor/lge/sdm845-common/proprietary/lib/libdpmfdmgr.so:system/lib/libdpmfdmgr.so \
    vendor/lge/sdm845-common/proprietary/lib/libdpmframework.so:system/lib/libdpmframework.so \
    vendor/lge/sdm845-common/proprietary/lib/libdpmnsrm.so:system/lib/libdpmnsrm.so \
    vendor/lge/sdm845-common/proprietary/lib/libdpmtcm.so:system/lib/libdpmtcm.so \
    vendor/lge/sdm845-common/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/lge/sdm845-common/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/lge/sdm845-common/proprietary/lib/libmmparser_lite.so:system/lib/libmmparser_lite.so \
    vendor/lge/sdm845-common/proprietary/lib/libmmrtpdecoder.so:system/lib/libmmrtpdecoder.so \
    vendor/lge/sdm845-common/proprietary/lib/libmmrtpencoder.so:system/lib/libmmrtpencoder.so \
    vendor/lge/sdm845-common/proprietary/lib/libqdMetaData.system.so:system/lib/libqdMetaData.system.so \
    vendor/lge/sdm845-common/proprietary/lib/libsdm-disp-apis.so:system/lib/libsdm-disp-apis.so \
    vendor/lge/sdm845-common/proprietary/lib/libwfdavenhancements.so:system/lib/libwfdavenhancements.so \
    vendor/lge/sdm845-common/proprietary/lib/libwfdcodecv4l2.so:system/lib/libwfdcodecv4l2.so \
    vendor/lge/sdm845-common/proprietary/lib/libwfdcommonutils.so:system/lib/libwfdcommonutils.so \
    vendor/lge/sdm845-common/proprietary/lib/libwfdconfigutils.so:system/lib/libwfdconfigutils.so \
    vendor/lge/sdm845-common/proprietary/lib/libwfdmminterface.so:system/lib/libwfdmminterface.so \
    vendor/lge/sdm845-common/proprietary/lib/libwfdmmsink.so:system/lib/libwfdmmsink.so \
    vendor/lge/sdm845-common/proprietary/lib/libwfdmmsrc.so:system/lib/libwfdmmsrc.so \
    vendor/lge/sdm845-common/proprietary/lib/libwfdnative.so:system/lib/libwfdnative.so \
    vendor/lge/sdm845-common/proprietary/lib/libwfdrtsp.so:system/lib/libwfdrtsp.so \
    vendor/lge/sdm845-common/proprietary/lib/libwfdservice.so:system/lib/libwfdservice.so \
    vendor/lge/sdm845-common/proprietary/lib/libwfdsm.so:system/lib/libwfdsm.so \
    vendor/lge/sdm845-common/proprietary/lib/libwfduibcinterface.so:system/lib/libwfduibcinterface.so \
    vendor/lge/sdm845-common/proprietary/lib/libwfduibcsink.so:system/lib/libwfduibcsink.so \
    vendor/lge/sdm845-common/proprietary/lib/libwfduibcsinkinterface.so:system/lib/libwfduibcsinkinterface.so \
    vendor/lge/sdm845-common/proprietary/lib/libwfduibcsrc.so:system/lib/libwfduibcsrc.so \
    vendor/lge/sdm845-common/proprietary/lib/libwfduibcsrcinterface.so:system/lib/libwfduibcsrcinterface.so \
    vendor/lge/sdm845-common/proprietary/lib/vendor.display.color@1.0.so:system/lib/vendor.display.color@1.0.so \
    vendor/lge/sdm845-common/proprietary/lib/vendor.qti.hardware.iop@1.0.so:system/lib/vendor.qti.hardware.iop@1.0.so \
    vendor/lge/sdm845-common/proprietary/lib/vendor.qti.hardware.iop@2.0.so:system/lib/vendor.qti.hardware.iop@2.0.so \
    vendor/lge/sdm845-common/proprietary/lib/vendor.qti.hardware.perf@1.0.so:system/lib/vendor.qti.hardware.perf@1.0.so \
    vendor/lge/sdm845-common/proprietary/lib64/com.qualcomm.qti.ant@1.0.so:system/lib64/com.qualcomm.qti.ant@1.0.so \
    vendor/lge/sdm845-common/proprietary/lib64/com.qualcomm.qti.dpm.api@1.0.so:system/lib64/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/lge/sdm845-common/proprietary/lib64/com.qualcomm.qti.wifidisplayhal@1.0.so:system/lib64/com.qualcomm.qti.wifidisplayhal@1.0.so \
    vendor/lge/sdm845-common/proprietary/lib64/libFileMux.so:system/lib64/libFileMux.so \
    vendor/lge/sdm845-common/proprietary/lib64/libOmxMux.so:system/lib64/libOmxMux.so \
    vendor/lge/sdm845-common/proprietary/lib64/libaptXHD_encoder.so:system/lib64/libaptXHD_encoder.so \
    vendor/lge/sdm845-common/proprietary/lib64/libaptX_encoder.so:system/lib64/libaptX_encoder.so \
    vendor/lge/sdm845-common/proprietary/lib64/libdisplayconfig.so:system/lib64/libdisplayconfig.so \
    vendor/lge/sdm845-common/proprietary/lib64/libdpmctmgr.so:system/lib64/libdpmctmgr.so \
    vendor/lge/sdm845-common/proprietary/lib64/libdpmfdmgr.so:system/lib64/libdpmfdmgr.so \
    vendor/lge/sdm845-common/proprietary/lib64/libdpmframework.so:system/lib64/libdpmframework.so \
    vendor/lge/sdm845-common/proprietary/lib64/libdpmnsrm.so:system/lib64/libdpmnsrm.so \
    vendor/lge/sdm845-common/proprietary/lib64/libdpmtcm.so:system/lib64/libdpmtcm.so \
    vendor/lge/sdm845-common/proprietary/lib64/libmmosal.so:system/lib64/libmmosal.so \
    vendor/lge/sdm845-common/proprietary/lib64/libmmparser.so:system/lib64/libmmparser.so \
    vendor/lge/sdm845-common/proprietary/lib64/libmmparser_lite.so:system/lib64/libmmparser_lite.so \
    vendor/lge/sdm845-common/proprietary/lib64/libmmrtpdecoder.so:system/lib64/libmmrtpdecoder.so \
    vendor/lge/sdm845-common/proprietary/lib64/libmmrtpencoder.so:system/lib64/libmmrtpencoder.so \
    vendor/lge/sdm845-common/proprietary/lib64/libqdMetaData.system.so:system/lib64/libqdMetaData.system.so \
    vendor/lge/sdm845-common/proprietary/lib64/libsdm-disp-apis.so:system/lib64/libsdm-disp-apis.so \
    vendor/lge/sdm845-common/proprietary/lib64/libwfdavenhancements.so:system/lib64/libwfdavenhancements.so \
    vendor/lge/sdm845-common/proprietary/lib64/libwfdcodecv4l2.so:system/lib64/libwfdcodecv4l2.so \
    vendor/lge/sdm845-common/proprietary/lib64/libwfdcommonutils.so:system/lib64/libwfdcommonutils.so \
    vendor/lge/sdm845-common/proprietary/lib64/libwfdconfigutils.so:system/lib64/libwfdconfigutils.so \
    vendor/lge/sdm845-common/proprietary/lib64/libwfdmminterface.so:system/lib64/libwfdmminterface.so \
    vendor/lge/sdm845-common/proprietary/lib64/libwfdmmsink.so:system/lib64/libwfdmmsink.so \
    vendor/lge/sdm845-common/proprietary/lib64/libwfdmmsrc.so:system/lib64/libwfdmmsrc.so \
    vendor/lge/sdm845-common/proprietary/lib64/libwfdnative.so:system/lib64/libwfdnative.so \
    vendor/lge/sdm845-common/proprietary/lib64/libwfdrtsp.so:system/lib64/libwfdrtsp.so \
    vendor/lge/sdm845-common/proprietary/lib64/libwfdservice.so:system/lib64/libwfdservice.so \
    vendor/lge/sdm845-common/proprietary/lib64/libwfdsm.so:system/lib64/libwfdsm.so \
    vendor/lge/sdm845-common/proprietary/lib64/libwfduibcinterface.so:system/lib64/libwfduibcinterface.so \
    vendor/lge/sdm845-common/proprietary/lib64/libwfduibcsink.so:system/lib64/libwfduibcsink.so \
    vendor/lge/sdm845-common/proprietary/lib64/libwfduibcsinkinterface.so:system/lib64/libwfduibcsinkinterface.so \
    vendor/lge/sdm845-common/proprietary/lib64/libwfduibcsrc.so:system/lib64/libwfduibcsrc.so \
    vendor/lge/sdm845-common/proprietary/lib64/libwfduibcsrcinterface.so:system/lib64/libwfduibcsrcinterface.so \
    vendor/lge/sdm845-common/proprietary/lib64/vendor.display.color@1.0.so:system/lib64/vendor.display.color@1.0.so \
    vendor/lge/sdm845-common/proprietary/lib64/vendor.qti.hardware.iop@1.0.so:system/lib64/vendor.qti.hardware.iop@1.0.so \
    vendor/lge/sdm845-common/proprietary/lib64/vendor.qti.hardware.iop@2.0.so:system/lib64/vendor.qti.hardware.iop@2.0.so \
    vendor/lge/sdm845-common/proprietary/lib64/vendor.qti.hardware.perf@1.0.so:system/lib64/vendor.qti.hardware.perf@1.0.so

PRODUCT_PACKAGES += \
    QtiTelephonyService \
    WfdService \
    CNEService \
    HotwordEnrollmentOKGoogleHEXAGON \
    HotwordEnrollmentXGoogleHEXAGON \
    qcrilmsgtunnel \
    WfdCommon
